---
# This action will publish the latest version to `npmjs.org` when a new tag is pushed
name: Publish Latest Version to NPM

on:
  push:
    tags:
      - v1.*
      - v0.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: percona-platform/checkout@v2

      - uses: percona-platform/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Clean up after tests
        run: git checkout -- tsconfig.json

      - name: Build the assets
        run: npm run build

      - name: Publish latest version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Deploying latest for ref: $GITHUB_REF"
          npm publish --tag latest --access public
