---
name: Publish Latest Version to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Parameter to pass to `npm version` (e.g: 'patch', 'minor', 'major', default: 'patch')"
        default: "patch"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: percona-platform/checkout@v3

      - uses: percona-platform/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"
          git config user.password "${ROBOT_TOKEN}"
          echo "GIT_USER=percona-platform-robot:${ROBOT_TOKEN}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Clean up after tests
        run: git checkout -- tsconfig.json

      - name: Build the assets
        run: npm run build

      - name: Bump version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: npm version $VERSION

      - name: Publish latest version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag latest --access public
